### ISSUE TITLE
[IUP question] No treeview widget with (sortable) columns?

### ISSUE THREAD

**Issue by vindarel** [lispnik/iup#54]
Hello,

This is a question about IUP, not the bindings. I already asked on the iup-users mailing list but I'll hopefully get more ideas here…

My concern is: is there no widget to display columns? And columns that we can sort?

Like GTK's Treeview or ltk't Treeview (or an html table):

![](https://python-gtk-3-tutorial.readthedocs.io/en/latest/_images/treeview_filter_example.png)

(https://python-gtk-3-tutorial.readthedocs.io/en/latest/_images/treeview_filter_example.png)

![](https://raw.githubusercontent.com/vindarel/ltk-tests/master/tree-columns.png)

The answer I received is: "Take a look at the IupMatrix and IupMatrixEx controls."

However, while IupMatrixEx looks quite nice and advanced, it is a spreadsheet and not a table :S Users would be surprised with this.

![IUP Matrix Test_028](https://user-images.githubusercontent.com/3721004/70834027-8bef4f00-1df9-11ea-82d5-c78251621eda.png)

My goal is to display tabular data: a book title, its author, its price, a cover image we can toggle,…

What does that inspire you all? 

Thanks.

**Comment by lispnik** [comment]
Hmmm I've just using a IupMatrix/MatrixEx for tabular stuff. I think you could make it work a lot like the Gtk example if you turn the borders off and make it readonly.

**Comment by vindarel** [comment]
ah thanks, I'll give it a try then.
