### ISSUE TITLE
Can't run iup from SLIME REPL

### ISSUE THREAD

**Issue by eid-setf** [lispnik/iup#58]
Hi! I'm using Windows and SBCL and I have a problem when executing functions that have iup code in them.

I get different results when running the hello world example from the README from different environments:
1. When running SBCL from the terminal and running the example it works and shows me a window
2. When running from emacs:
  a. running the function using `C-x C-e` works and shows a window
  b. but when running from the slime REPL it just blocks the REPL and never shows a window 

Mind you I tried every combination of sly/slime (even emacs' run-lisp) and SBCL/CCL. Thanks!

**Comment by vindarel** [comment]
Hello, I suppose the maintainer will want to see an example code that blocks in Emacs. I'll try myself too. I've had success last time I tried.

**Comment by eid-setf** [comment]
Try running the main function in the following code from the slime REPL. For me it just hangs Emacs, but when I run it from terminal SBCL it works as expected

```lisp
(eval-when (:compile-toplevel :load-toplevel :execute)
  (ql:quickload "iup"))

(defun hello ()
  (iup:with-iup ()
    (let* ((label (iup:label :title (format nil "Hello, World!~%IUP ~A~%~A ~A"
                                            (iup:version)
                                            (lisp-implementation-type)
                                            (lisp-implementation-version))))
           (dialog (iup:dialog label :title "Hello, World!")))
      (iup:show dialog)
      (iup:main-loop))))

(defun main ()
  #-sbcl (hello)
  #+sbcl
  (sb-int:with-float-traps-masked
      (:divide-by-zero :invalid)
    (hello)))
```

**Comment by vindarel** [comment]
Works for me© !

    (main) => little IUP window, the REPL still works once I close the window.

Emacs 27.1, SBCL 2.0.1.debian, installed IUP with `(ql:quickload "tecgraf-libs")`.

NB: the little window appeared in the background, it didn't get the focus, so if I didn't look for it and I had Emacs in full screen, it would be as if Emacs was hanging, but it was waiting for me to close the window. Just in case ;)

**Comment by eid-setf** [comment]
Hi! It seems the problem has something to do with Windows. I saw from your comment that you use Linux, so I tried to run the same code from an Ubuntu WSL, and It worked like you described.

**Comment by lispnik** [comment]
@ahmadv0 try running sbcl etc. on Windows, by prefixing it with `cmd /c`, so for example:

```
 (setq sly-lisp-implementations
           '((ccl ("cmd" "/c" "wx86cl64"))
             (sbcl ("cmd" "/c" "sbcl.exe" "--dynamic-space-size" "2048"))))
...
```

This also fixes problems with running cl-sdl2 on Windows via slime/sly, for me at least.

**Comment by eid-setf** [comment]
@lispnik Thank you it worked! but It would've been nice if it was documented

**Comment by lispnik** [comment]
Yes, that is a good idea. I've added it to the README: https://github.com/lispnik/iup/blob/master/README.org#running-gui-applications-on-windows-using-slime-or-sly
