### ISSUE TITLE
Iup-im depends on im and im-cffi, which don't seem to exist

### ISSUE THREAD

**Issue by rationalis-petra** [lispnik/iup#60]
When trying to load iup-im with:

```lisp
(ql:quickload '(:iup iup-im))
```

Quicklisp fails with error  "System im was not found". If I comment out the dependency, then im-iup-cffi will similarly fail to find dependency "im-cffi". It seems only to require this dependency for `im-cffi::im-image`. I have been unable to find references to either of these systems either in this repository, or any of your related repositories.

**Comment by lispnik** [comment]
Hi, I should do a better job of documenting but the repo is https://github.com/lispnik/im

**Comment by rationalis-petra** [comment]
Thanks! Feel free to close.
